// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamestate.proto

package gamestate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BulletType int32

const (
	BulletType_NORMAL BulletType = 0
)

var BulletType_name = map[int32]string{
	0: "NORMAL",
}
var BulletType_value = map[string]int32{
	"NORMAL": 0,
}

func (x BulletType) String() string {
	return proto.EnumName(BulletType_name, int32(x))
}
func (BulletType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{0}
}

// State for both Bullet and Ship
type State int32

const (
	State_SPAWN  State = 0
	State_ALIVE  State = 1
	State_DEAD   State = 2
	State_INVULN State = 3
	// TODO do I need destroy in addition to DEAD ?
	State_DESTROY State = 4
)

var State_name = map[int32]string{
	0: "SPAWN",
	1: "ALIVE",
	2: "DEAD",
	3: "INVULN",
	4: "DESTROY",
}
var State_value = map[string]int32{
	"SPAWN":   0,
	"ALIVE":   1,
	"DEAD":    2,
	"INVULN":  3,
	"DESTROY": 4,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{1}
}

type ShipTypeEnum int32

const (
	ShipTypeEnum_HEAVY   ShipTypeEnum = 0
	ShipTypeEnum_FORWARD ShipTypeEnum = 1
	ShipTypeEnum_SCOUT   ShipTypeEnum = 2
)

var ShipTypeEnum_name = map[int32]string{
	0: "HEAVY",
	1: "FORWARD",
	2: "SCOUT",
}
var ShipTypeEnum_value = map[string]int32{
	"HEAVY":   0,
	"FORWARD": 1,
	"SCOUT":   2,
}

func (x ShipTypeEnum) String() string {
	return proto.EnumName(ShipTypeEnum_name, int32(x))
}
func (ShipTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{2}
}

type GenericMessage_MessageTypeEnum int32

const (
	GenericMessage_GAME_STATE_UPDATE GenericMessage_MessageTypeEnum = 0
	GenericMessage_SHIP_UPDATE       GenericMessage_MessageTypeEnum = 1
	GenericMessage_JOIN_GAME         GenericMessage_MessageTypeEnum = 2
	GenericMessage_SET_TEAM_AND_SHIP GenericMessage_MessageTypeEnum = 3
)

var GenericMessage_MessageTypeEnum_name = map[int32]string{
	0: "GAME_STATE_UPDATE",
	1: "SHIP_UPDATE",
	2: "JOIN_GAME",
	3: "SET_TEAM_AND_SHIP",
}
var GenericMessage_MessageTypeEnum_value = map[string]int32{
	"GAME_STATE_UPDATE": 0,
	"SHIP_UPDATE":       1,
	"JOIN_GAME":         2,
	"SET_TEAM_AND_SHIP": 3,
}

func (x GenericMessage_MessageTypeEnum) String() string {
	return proto.EnumName(GenericMessage_MessageTypeEnum_name, int32(x))
}
func (GenericMessage_MessageTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{0, 0}
}

// This is the only message we send and recieve
// MessageType lets us determine how to unpack the bytes portion.
type GenericMessage struct {
	MessageType          GenericMessage_MessageTypeEnum `protobuf:"varint,1,opt,name=messageType,proto3,enum=GenericMessage_MessageTypeEnum" json:"messageType,omitempty"`
	Data                 []byte                         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GenericMessage) Reset()         { *m = GenericMessage{} }
func (m *GenericMessage) String() string { return proto.CompactTextString(m) }
func (*GenericMessage) ProtoMessage()    {}
func (*GenericMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{0}
}
func (m *GenericMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericMessage.Unmarshal(m, b)
}
func (m *GenericMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericMessage.Marshal(b, m, deterministic)
}
func (dst *GenericMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericMessage.Merge(dst, src)
}
func (m *GenericMessage) XXX_Size() int {
	return xxx_messageInfo_GenericMessage.Size(m)
}
func (m *GenericMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GenericMessage proto.InternalMessageInfo

func (m *GenericMessage) GetMessageType() GenericMessage_MessageTypeEnum {
	if m != nil {
		return m.MessageType
	}
	return GenericMessage_GAME_STATE_UPDATE
}

func (m *GenericMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Our list of ships
type GameState struct {
	// Updates for pretty much all non-static game objects
	Ships                []*Ship           `protobuf:"bytes,1,rep,name=ships,proto3" json:"ships,omitempty"`
	Bullets              []*Bullet         `protobuf:"bytes,2,rep,name=bullets,proto3" json:"bullets,omitempty"`
	Scores               []*Score          `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty"`
	SetTeamAndShip       []*SetTeamAndShip `protobuf:"bytes,4,rep,name=setTeamAndShip,proto3" json:"setTeamAndShip,omitempty"`
	PlayersJoining       []*PlayerJoin     `protobuf:"bytes,5,rep,name=playersJoining,proto3" json:"playersJoining,omitempty"`
	PlayerLeave          []int32           `protobuf:"varint,6,rep,packed,name=PlayerLeave,proto3" json:"PlayerLeave,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{1}
}
func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (dst *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(dst, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetShips() []*Ship {
	if m != nil {
		return m.Ships
	}
	return nil
}

func (m *GameState) GetBullets() []*Bullet {
	if m != nil {
		return m.Bullets
	}
	return nil
}

func (m *GameState) GetScores() []*Score {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *GameState) GetSetTeamAndShip() []*SetTeamAndShip {
	if m != nil {
		return m.SetTeamAndShip
	}
	return nil
}

func (m *GameState) GetPlayersJoining() []*PlayerJoin {
	if m != nil {
		return m.PlayersJoining
	}
	return nil
}

func (m *GameState) GetPlayerLeave() []int32 {
	if m != nil {
		return m.PlayerLeave
	}
	return nil
}

type PlayerJoin struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerJoin) Reset()         { *m = PlayerJoin{} }
func (m *PlayerJoin) String() string { return proto.CompactTextString(m) }
func (*PlayerJoin) ProtoMessage()    {}
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{2}
}
func (m *PlayerJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerJoin.Unmarshal(m, b)
}
func (m *PlayerJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerJoin.Marshal(b, m, deterministic)
}
func (dst *PlayerJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerJoin.Merge(dst, src)
}
func (m *PlayerJoin) XXX_Size() int {
	return xxx_messageInfo_PlayerJoin.Size(m)
}
func (m *PlayerJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerJoin.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerJoin proto.InternalMessageInfo

func (m *PlayerJoin) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerJoin) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type Score struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kills                int32    `protobuf:"varint,2,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths               int32    `protobuf:"varint,3,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Assists              int32    `protobuf:"varint,4,opt,name=assists,proto3" json:"assists,omitempty"`
	Goals                int32    `protobuf:"varint,5,opt,name=goals,proto3" json:"goals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Score) Reset()         { *m = Score{} }
func (m *Score) String() string { return proto.CompactTextString(m) }
func (*Score) ProtoMessage()    {}
func (*Score) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{3}
}
func (m *Score) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Score.Unmarshal(m, b)
}
func (m *Score) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Score.Marshal(b, m, deterministic)
}
func (dst *Score) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Score.Merge(dst, src)
}
func (m *Score) XXX_Size() int {
	return xxx_messageInfo_Score.Size(m)
}
func (m *Score) XXX_DiscardUnknown() {
	xxx_messageInfo_Score.DiscardUnknown(m)
}

var xxx_messageInfo_Score proto.InternalMessageInfo

func (m *Score) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Score) GetKills() int32 {
	if m != nil {
		return m.Kills
	}
	return 0
}

func (m *Score) GetDeaths() int32 {
	if m != nil {
		return m.Deaths
	}
	return 0
}

func (m *Score) GetAssists() int32 {
	if m != nil {
		return m.Assists
	}
	return 0
}

func (m *Score) GetGoals() int32 {
	if m != nil {
		return m.Goals
	}
	return 0
}

type Bullet struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int32      `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Type                 BulletType `protobuf:"varint,3,opt,name=type,proto3,enum=BulletType" json:"type,omitempty"`
	State                State      `protobuf:"varint,4,opt,name=state,proto3,enum=State" json:"state,omitempty"`
	XPos                 float32    `protobuf:"fixed32,5,opt,name=xPos,proto3" json:"xPos,omitempty"`
	YPos                 float32    `protobuf:"fixed32,6,opt,name=yPos,proto3" json:"yPos,omitempty"`
	XVel                 float32    `protobuf:"fixed32,7,opt,name=xVel,proto3" json:"xVel,omitempty"`
	YVel                 float32    `protobuf:"fixed32,8,opt,name=yVel,proto3" json:"yVel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Bullet) Reset()         { *m = Bullet{} }
func (m *Bullet) String() string { return proto.CompactTextString(m) }
func (*Bullet) ProtoMessage()    {}
func (*Bullet) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{4}
}
func (m *Bullet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bullet.Unmarshal(m, b)
}
func (m *Bullet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bullet.Marshal(b, m, deterministic)
}
func (dst *Bullet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bullet.Merge(dst, src)
}
func (m *Bullet) XXX_Size() int {
	return xxx_messageInfo_Bullet.Size(m)
}
func (m *Bullet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bullet.DiscardUnknown(m)
}

var xxx_messageInfo_Bullet proto.InternalMessageInfo

func (m *Bullet) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bullet) GetOwnerId() int32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Bullet) GetType() BulletType {
	if m != nil {
		return m.Type
	}
	return BulletType_NORMAL
}

func (m *Bullet) GetState() State {
	if m != nil {
		return m.State
	}
	return State_SPAWN
}

func (m *Bullet) GetXPos() float32 {
	if m != nil {
		return m.XPos
	}
	return 0
}

func (m *Bullet) GetYPos() float32 {
	if m != nil {
		return m.YPos
	}
	return 0
}

func (m *Bullet) GetXVel() float32 {
	if m != nil {
		return m.XVel
	}
	return 0
}

func (m *Bullet) GetYVel() float32 {
	if m != nil {
		return m.YVel
	}
	return 0
}

type Ship struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                State    `protobuf:"varint,2,opt,name=state,proto3,enum=State" json:"state,omitempty"`
	XPos                 float32  `protobuf:"fixed32,3,opt,name=xPos,proto3" json:"xPos,omitempty"`
	YPos                 float32  `protobuf:"fixed32,4,opt,name=yPos,proto3" json:"yPos,omitempty"`
	XVel                 float32  `protobuf:"fixed32,5,opt,name=xVel,proto3" json:"xVel,omitempty"`
	YVel                 float32  `protobuf:"fixed32,6,opt,name=yVel,proto3" json:"yVel,omitempty"`
	Rot                  float32  `protobuf:"fixed32,7,opt,name=rot,proto3" json:"rot,omitempty"`
	RotVel               float32  `protobuf:"fixed32,8,opt,name=rotVel,proto3" json:"rotVel,omitempty"`
	Health               int32    `protobuf:"varint,9,opt,name=health,proto3" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ship) Reset()         { *m = Ship{} }
func (m *Ship) String() string { return proto.CompactTextString(m) }
func (*Ship) ProtoMessage()    {}
func (*Ship) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{5}
}
func (m *Ship) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ship.Unmarshal(m, b)
}
func (m *Ship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ship.Marshal(b, m, deterministic)
}
func (dst *Ship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ship.Merge(dst, src)
}
func (m *Ship) XXX_Size() int {
	return xxx_messageInfo_Ship.Size(m)
}
func (m *Ship) XXX_DiscardUnknown() {
	xxx_messageInfo_Ship.DiscardUnknown(m)
}

var xxx_messageInfo_Ship proto.InternalMessageInfo

func (m *Ship) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Ship) GetState() State {
	if m != nil {
		return m.State
	}
	return State_SPAWN
}

func (m *Ship) GetXPos() float32 {
	if m != nil {
		return m.XPos
	}
	return 0
}

func (m *Ship) GetYPos() float32 {
	if m != nil {
		return m.YPos
	}
	return 0
}

func (m *Ship) GetXVel() float32 {
	if m != nil {
		return m.XVel
	}
	return 0
}

func (m *Ship) GetYVel() float32 {
	if m != nil {
		return m.YVel
	}
	return 0
}

func (m *Ship) GetRot() float32 {
	if m != nil {
		return m.Rot
	}
	return 0
}

func (m *Ship) GetRotVel() float32 {
	if m != nil {
		return m.RotVel
	}
	return 0
}

func (m *Ship) GetHealth() int32 {
	if m != nil {
		return m.Health
	}
	return 0
}

// TODO Should be a packed byte instead of a bool
type ShipUpdate struct {
	RotLeft              bool     `protobuf:"varint,1,opt,name=rotLeft,proto3" json:"rotLeft,omitempty"`
	RotRight             bool     `protobuf:"varint,2,opt,name=rotRight,proto3" json:"rotRight,omitempty"`
	Thrust               bool     `protobuf:"varint,3,opt,name=thrust,proto3" json:"thrust,omitempty"`
	Ability1             bool     `protobuf:"varint,4,opt,name=ability1,proto3" json:"ability1,omitempty"`
	Ability2             bool     `protobuf:"varint,5,opt,name=ability2,proto3" json:"ability2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipUpdate) Reset()         { *m = ShipUpdate{} }
func (m *ShipUpdate) String() string { return proto.CompactTextString(m) }
func (*ShipUpdate) ProtoMessage()    {}
func (*ShipUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{6}
}
func (m *ShipUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipUpdate.Unmarshal(m, b)
}
func (m *ShipUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipUpdate.Marshal(b, m, deterministic)
}
func (dst *ShipUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipUpdate.Merge(dst, src)
}
func (m *ShipUpdate) XXX_Size() int {
	return xxx_messageInfo_ShipUpdate.Size(m)
}
func (m *ShipUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ShipUpdate proto.InternalMessageInfo

func (m *ShipUpdate) GetRotLeft() bool {
	if m != nil {
		return m.RotLeft
	}
	return false
}

func (m *ShipUpdate) GetRotRight() bool {
	if m != nil {
		return m.RotRight
	}
	return false
}

func (m *ShipUpdate) GetThrust() bool {
	if m != nil {
		return m.Thrust
	}
	return false
}

func (m *ShipUpdate) GetAbility1() bool {
	if m != nil {
		return m.Ability1
	}
	return false
}

func (m *ShipUpdate) GetAbility2() bool {
	if m != nil {
		return m.Ability2
	}
	return false
}

type JoinGame struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGame) Reset()         { *m = JoinGame{} }
func (m *JoinGame) String() string { return proto.CompactTextString(m) }
func (*JoinGame) ProtoMessage()    {}
func (*JoinGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{7}
}
func (m *JoinGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGame.Unmarshal(m, b)
}
func (m *JoinGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGame.Marshal(b, m, deterministic)
}
func (dst *JoinGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGame.Merge(dst, src)
}
func (m *JoinGame) XXX_Size() int {
	return xxx_messageInfo_JoinGame.Size(m)
}
func (m *JoinGame) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGame.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGame proto.InternalMessageInfo

func (m *JoinGame) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type SetTeamAndShip struct {
	Team                 int32        `protobuf:"varint,1,opt,name=team,proto3" json:"team,omitempty"`
	ShipType             ShipTypeEnum `protobuf:"varint,2,opt,name=shipType,proto3,enum=ShipTypeEnum" json:"shipType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetTeamAndShip) Reset()         { *m = SetTeamAndShip{} }
func (m *SetTeamAndShip) String() string { return proto.CompactTextString(m) }
func (*SetTeamAndShip) ProtoMessage()    {}
func (*SetTeamAndShip) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{8}
}
func (m *SetTeamAndShip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTeamAndShip.Unmarshal(m, b)
}
func (m *SetTeamAndShip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTeamAndShip.Marshal(b, m, deterministic)
}
func (dst *SetTeamAndShip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTeamAndShip.Merge(dst, src)
}
func (m *SetTeamAndShip) XXX_Size() int {
	return xxx_messageInfo_SetTeamAndShip.Size(m)
}
func (m *SetTeamAndShip) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTeamAndShip.DiscardUnknown(m)
}

var xxx_messageInfo_SetTeamAndShip proto.InternalMessageInfo

func (m *SetTeamAndShip) GetTeam() int32 {
	if m != nil {
		return m.Team
	}
	return 0
}

func (m *SetTeamAndShip) GetShipType() ShipTypeEnum {
	if m != nil {
		return m.ShipType
	}
	return ShipTypeEnum_HEAVY
}

type UpdateTeamAndShip struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Team                 int32        `protobuf:"varint,2,opt,name=team,proto3" json:"team,omitempty"`
	ShipType             ShipTypeEnum `protobuf:"varint,3,opt,name=shipType,proto3,enum=ShipTypeEnum" json:"shipType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateTeamAndShip) Reset()         { *m = UpdateTeamAndShip{} }
func (m *UpdateTeamAndShip) String() string { return proto.CompactTextString(m) }
func (*UpdateTeamAndShip) ProtoMessage()    {}
func (*UpdateTeamAndShip) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{9}
}
func (m *UpdateTeamAndShip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTeamAndShip.Unmarshal(m, b)
}
func (m *UpdateTeamAndShip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTeamAndShip.Marshal(b, m, deterministic)
}
func (dst *UpdateTeamAndShip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTeamAndShip.Merge(dst, src)
}
func (m *UpdateTeamAndShip) XXX_Size() int {
	return xxx_messageInfo_UpdateTeamAndShip.Size(m)
}
func (m *UpdateTeamAndShip) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTeamAndShip.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTeamAndShip proto.InternalMessageInfo

func (m *UpdateTeamAndShip) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTeamAndShip) GetTeam() int32 {
	if m != nil {
		return m.Team
	}
	return 0
}

func (m *UpdateTeamAndShip) GetShipType() ShipTypeEnum {
	if m != nil {
		return m.ShipType
	}
	return ShipTypeEnum_HEAVY
}

type Login struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_fea72ad993a13c58, []int{10}
}
func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (dst *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(dst, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*GenericMessage)(nil), "GenericMessage")
	proto.RegisterType((*GameState)(nil), "GameState")
	proto.RegisterType((*PlayerJoin)(nil), "PlayerJoin")
	proto.RegisterType((*Score)(nil), "Score")
	proto.RegisterType((*Bullet)(nil), "Bullet")
	proto.RegisterType((*Ship)(nil), "Ship")
	proto.RegisterType((*ShipUpdate)(nil), "ShipUpdate")
	proto.RegisterType((*JoinGame)(nil), "JoinGame")
	proto.RegisterType((*SetTeamAndShip)(nil), "SetTeamAndShip")
	proto.RegisterType((*UpdateTeamAndShip)(nil), "UpdateTeamAndShip")
	proto.RegisterType((*Login)(nil), "Login")
	proto.RegisterEnum("BulletType", BulletType_name, BulletType_value)
	proto.RegisterEnum("State", State_name, State_value)
	proto.RegisterEnum("ShipTypeEnum", ShipTypeEnum_name, ShipTypeEnum_value)
	proto.RegisterEnum("GenericMessage_MessageTypeEnum", GenericMessage_MessageTypeEnum_name, GenericMessage_MessageTypeEnum_value)
}

func init() { proto.RegisterFile("gamestate.proto", fileDescriptor_gamestate_fea72ad993a13c58) }

var fileDescriptor_gamestate_fea72ad993a13c58 = []byte{
	// 814 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x4d, 0x8f, 0xdb, 0x36,
	0x10, 0x5d, 0x49, 0x96, 0x2c, 0x8f, 0x13, 0xaf, 0x42, 0xb4, 0x05, 0xd1, 0x16, 0x8d, 0xab, 0xd3,
	0x76, 0x0f, 0x06, 0xb2, 0x39, 0xb4, 0xb7, 0x56, 0xad, 0xd5, 0x8d, 0x03, 0x7f, 0x81, 0xd2, 0x3a,
	0xc8, 0xc9, 0xa0, 0x23, 0xd6, 0x16, 0x2a, 0x5b, 0x86, 0x48, 0x37, 0xf1, 0xdf, 0xe8, 0x3f, 0xea,
	0xa5, 0xe8, 0x7f, 0xea, 0xa5, 0x18, 0x4a, 0xf2, 0x57, 0xb6, 0xb9, 0xf1, 0xbd, 0x79, 0x43, 0xbe,
	0xd1, 0x0c, 0x29, 0xb8, 0x5e, 0xf2, 0xb5, 0x90, 0x8a, 0x2b, 0xd1, 0xdb, 0x16, 0xb9, 0xca, 0xfd,
	0x7f, 0x0c, 0xe8, 0xdc, 0x8b, 0x8d, 0x28, 0xd2, 0x77, 0x23, 0x21, 0x25, 0x5f, 0x0a, 0x12, 0x40,
	0x7b, 0x5d, 0x2e, 0xe3, 0xfd, 0x56, 0x50, 0xa3, 0x6b, 0xdc, 0x74, 0xee, 0x9e, 0xf7, 0xce, 0x55,
	0xbd, 0xd1, 0x51, 0x12, 0x6e, 0x76, 0x6b, 0x76, 0x9a, 0x43, 0x08, 0x34, 0x12, 0xae, 0x38, 0x35,
	0xbb, 0xc6, 0xcd, 0x13, 0xa6, 0xd7, 0xfe, 0x1c, 0xae, 0x2f, 0x72, 0xc8, 0xe7, 0xf0, 0xec, 0x3e,
	0x18, 0x85, 0xf3, 0x28, 0x0e, 0xe2, 0x70, 0xfe, 0x30, 0xed, 0x07, 0x71, 0xe8, 0x5d, 0x91, 0x6b,
	0x68, 0x47, 0xaf, 0x06, 0xd3, 0x9a, 0x30, 0xc8, 0x53, 0x68, 0xbd, 0x9e, 0x0c, 0xc6, 0x73, 0x14,
	0x7b, 0x26, 0xa6, 0x45, 0x61, 0x3c, 0x8f, 0xc3, 0x60, 0x34, 0x0f, 0xc6, 0xfd, 0x39, 0x8a, 0x3d,
	0xcb, 0xff, 0xd7, 0x80, 0xd6, 0x3d, 0x5f, 0x8b, 0x08, 0xcb, 0x23, 0x5f, 0x81, 0x2d, 0x57, 0xe9,
	0x56, 0x52, 0xa3, 0x6b, 0xdd, 0xb4, 0xef, 0xec, 0x5e, 0xb4, 0x4a, 0xb7, 0xac, 0xe4, 0xc8, 0xb7,
	0xd0, 0x5c, 0xec, 0xb2, 0x4c, 0x28, 0x49, 0x4d, 0x1d, 0x6e, 0xf6, 0x7e, 0xd6, 0x98, 0xd5, 0x3c,
	0xf9, 0x06, 0x1c, 0xf9, 0x2e, 0x2f, 0x84, 0xa4, 0x96, 0x56, 0x38, 0xbd, 0x08, 0x21, 0xab, 0x58,
	0xf2, 0x3d, 0x74, 0xa4, 0x50, 0xb1, 0xe0, 0xeb, 0x60, 0x93, 0xe0, 0xde, 0xb4, 0xa1, 0x75, 0xd7,
	0xbd, 0xe8, 0x8c, 0x66, 0x17, 0x32, 0xf2, 0x12, 0x3a, 0xdb, 0x8c, 0xef, 0x45, 0x21, 0x5f, 0xe7,
	0xe9, 0x26, 0xdd, 0x2c, 0xa9, 0xad, 0x13, 0xdb, 0xbd, 0xa9, 0xa6, 0x91, 0x65, 0x17, 0x12, 0xd2,
	0x85, 0x76, 0x19, 0x1d, 0x0a, 0xfe, 0x87, 0xa0, 0x4e, 0xd7, 0xba, 0xb1, 0xd9, 0x29, 0xe5, 0xff,
	0x00, 0x70, 0xcc, 0x27, 0x1d, 0x30, 0xd3, 0x44, 0xb7, 0xce, 0x66, 0x66, 0x9a, 0x90, 0x2f, 0xc1,
	0xdd, 0x49, 0x51, 0x8c, 0xf9, 0x5a, 0xe8, 0xa6, 0xb4, 0xd8, 0x01, 0xfb, 0x3b, 0xb0, 0x75, 0x69,
	0x1f, 0x25, 0x7d, 0x06, 0xf6, 0xef, 0x69, 0x96, 0x49, 0x9d, 0x61, 0xb3, 0x12, 0x90, 0x2f, 0xc0,
	0x49, 0x04, 0x57, 0x2b, 0xfc, 0x30, 0x48, 0x57, 0x88, 0x50, 0x68, 0x72, 0x29, 0x53, 0xa9, 0x24,
	0x6d, 0xe8, 0x40, 0x0d, 0x71, 0x9f, 0x65, 0xce, 0x33, 0x49, 0xed, 0x72, 0x1f, 0x0d, 0xfc, 0xbf,
	0x0c, 0x70, 0xca, 0x8f, 0xfe, 0xd1, 0xc1, 0x14, 0x9a, 0xf9, 0xfb, 0x8d, 0x28, 0x06, 0x49, 0x75,
	0x74, 0x0d, 0xc9, 0x73, 0x68, 0x28, 0x1c, 0x4a, 0x4b, 0x0f, 0x65, 0xbb, 0xea, 0x1a, 0x0e, 0x14,
	0xd3, 0x01, 0xf2, 0x35, 0xd8, 0x7a, 0xbc, 0xb5, 0x87, 0x0e, 0x76, 0x0d, 0x11, 0x2b, 0x49, 0x9c,
	0xcb, 0x0f, 0xd3, 0xbc, 0x34, 0x62, 0x32, 0xbd, 0x46, 0x6e, 0x8f, 0x9c, 0x53, 0x72, 0xfb, 0x8a,
	0xfb, 0x30, 0x13, 0x19, 0x6d, 0x56, 0xba, 0x99, 0xc8, 0xb4, 0x0e, 0x39, 0xb7, 0xd2, 0xcd, 0x44,
	0xe6, 0xff, 0x6d, 0x40, 0x43, 0x37, 0xf5, 0xb2, 0x82, 0x83, 0x0d, 0xf3, 0x53, 0x36, 0xac, 0x47,
	0x6c, 0x34, 0x1e, 0xb1, 0x61, 0x3f, 0x62, 0xc3, 0x39, 0xda, 0x20, 0x1e, 0x58, 0x45, 0xae, 0x2a,
	0xb7, 0xb8, 0xc4, 0x26, 0x15, 0xb9, 0x3a, 0xda, 0xad, 0x10, 0xf2, 0x2b, 0xc1, 0x33, 0xb5, 0xa2,
	0xad, 0xb2, 0x79, 0x25, 0xf2, 0xff, 0x34, 0x00, 0xb0, 0x90, 0x87, 0x6d, 0x82, 0x06, 0x29, 0x34,
	0x8b, 0x5c, 0x0d, 0xc5, 0x6f, 0x4a, 0xd7, 0xe4, 0xb2, 0x1a, 0xe2, 0x20, 0x15, 0xb9, 0x62, 0xe9,
	0x72, 0xa5, 0x74, 0x6d, 0x2e, 0x3b, 0x60, 0xdc, 0x5c, 0xad, 0x8a, 0x9d, 0x54, 0xba, 0x30, 0x97,
	0x55, 0x08, 0x73, 0xf8, 0x22, 0xcd, 0x52, 0xb5, 0x7f, 0xa1, 0xcb, 0x73, 0xd9, 0x01, 0x9f, 0xc4,
	0xee, 0x74, 0x99, 0xc7, 0xd8, 0x9d, 0xef, 0x83, 0x8b, 0xc3, 0x8c, 0x77, 0x1a, 0xf7, 0xc6, 0xa7,
	0x6b, 0x50, 0x7f, 0xe4, 0x0a, 0xf9, 0x13, 0xe8, 0x9c, 0xdf, 0x37, 0xfc, 0x40, 0x4a, 0xf0, 0x75,
	0xa5, 0xd3, 0x6b, 0xf2, 0x1d, 0xb8, 0x78, 0xf1, 0xf5, 0x7b, 0x56, 0x76, 0xe4, 0xa9, 0x7e, 0x0f,
	0x0e, 0xaf, 0xd7, 0x21, 0xec, 0x2f, 0xe0, 0x59, 0xf9, 0x11, 0x4e, 0xf7, 0xbc, 0x6c, 0x6f, 0x7d,
	0x86, 0xf9, 0x3f, 0x67, 0x58, 0x9f, 0x3e, 0xe3, 0x47, 0xb0, 0x87, 0xf9, 0x32, 0xdd, 0x9c, 0x5d,
	0x4b, 0xe3, 0xfc, 0x5a, 0x62, 0x6c, 0xcb, 0xa5, 0x7c, 0x9f, 0x17, 0x49, 0x7d, 0x65, 0x6b, 0x7c,
	0x4b, 0x01, 0x8e, 0x93, 0x4f, 0x00, 0x9c, 0xf1, 0x84, 0x8d, 0x82, 0xa1, 0x77, 0x75, 0xfb, 0x13,
	0xd8, 0xe5, 0xfb, 0xd7, 0x02, 0x3b, 0x9a, 0x06, 0x6f, 0xc6, 0xde, 0x15, 0x2e, 0x83, 0xe1, 0x60,
	0x86, 0x2f, 0xa9, 0x0b, 0x8d, 0x7e, 0x18, 0xf4, 0x3d, 0x13, 0x93, 0x06, 0xe3, 0xd9, 0xc3, 0x70,
	0xec, 0x59, 0xa4, 0x0d, 0xcd, 0x7e, 0x18, 0xc5, 0x6c, 0xf2, 0xd6, 0x6b, 0xdc, 0xbe, 0x80, 0x27,
	0xa7, 0xb6, 0x31, 0xfb, 0x55, 0x18, 0xcc, 0xde, 0x7a, 0x57, 0xa8, 0xfb, 0x75, 0xc2, 0xde, 0x04,
	0xac, 0xef, 0x19, 0xfa, 0x80, 0x5f, 0x26, 0x0f, 0xb1, 0x67, 0x2e, 0x1c, 0xfd, 0x2f, 0x79, 0xf9,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0xac, 0x28, 0x75, 0x5e, 0x06, 0x00, 0x00,
}
