// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamestate.proto

package gamestate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenericMessage_MessageTypeEnum int32

const (
	GenericMessage_GAME_STATE_UPDATE GenericMessage_MessageTypeEnum = 0
	GenericMessage_SHIP_UPDATE       GenericMessage_MessageTypeEnum = 1
	GenericMessage_NEW_SHIP          GenericMessage_MessageTypeEnum = 2
)

var GenericMessage_MessageTypeEnum_name = map[int32]string{
	0: "GAME_STATE_UPDATE",
	1: "SHIP_UPDATE",
	2: "NEW_SHIP",
}
var GenericMessage_MessageTypeEnum_value = map[string]int32{
	"GAME_STATE_UPDATE": 0,
	"SHIP_UPDATE":       1,
	"NEW_SHIP":          2,
}

func (x GenericMessage_MessageTypeEnum) String() string {
	return proto.EnumName(GenericMessage_MessageTypeEnum_name, int32(x))
}
func (GenericMessage_MessageTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_7bbe1fe9df4558eb, []int{0, 0}
}

// This is the only message we send and recieve
// MessageType lets us determine how to unpack the bytes portion.
type GenericMessage struct {
	MessageType          GenericMessage_MessageTypeEnum `protobuf:"varint,1,opt,name=messageType,proto3,enum=GenericMessage_MessageTypeEnum" json:"messageType,omitempty"`
	Data                 []byte                         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GenericMessage) Reset()         { *m = GenericMessage{} }
func (m *GenericMessage) String() string { return proto.CompactTextString(m) }
func (*GenericMessage) ProtoMessage()    {}
func (*GenericMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_7bbe1fe9df4558eb, []int{0}
}
func (m *GenericMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericMessage.Unmarshal(m, b)
}
func (m *GenericMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericMessage.Marshal(b, m, deterministic)
}
func (dst *GenericMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericMessage.Merge(dst, src)
}
func (m *GenericMessage) XXX_Size() int {
	return xxx_messageInfo_GenericMessage.Size(m)
}
func (m *GenericMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GenericMessage proto.InternalMessageInfo

func (m *GenericMessage) GetMessageType() GenericMessage_MessageTypeEnum {
	if m != nil {
		return m.MessageType
	}
	return GenericMessage_GAME_STATE_UPDATE
}

func (m *GenericMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Ship struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XPos                 float32        `protobuf:"fixed32,3,opt,name=xPos,proto3" json:"xPos,omitempty"`
	YPos                 float32        `protobuf:"fixed32,4,opt,name=yPos,proto3" json:"yPos,omitempty"`
	XVel                 float32        `protobuf:"fixed32,5,opt,name=xVel,proto3" json:"xVel,omitempty"`
	YVel                 float32        `protobuf:"fixed32,6,opt,name=yVel,proto3" json:"yVel,omitempty"`
	Rot                  float32        `protobuf:"fixed32,7,opt,name=rot,proto3" json:"rot,omitempty"`
	RotVel               float32        `protobuf:"fixed32,8,opt,name=rotVel,proto3" json:"rotVel,omitempty"`
	Bullets              []*Ship_Bullet `protobuf:"bytes,9,rep,name=bullets,proto3" json:"bullets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Ship) Reset()         { *m = Ship{} }
func (m *Ship) String() string { return proto.CompactTextString(m) }
func (*Ship) ProtoMessage()    {}
func (*Ship) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_7bbe1fe9df4558eb, []int{1}
}
func (m *Ship) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ship.Unmarshal(m, b)
}
func (m *Ship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ship.Marshal(b, m, deterministic)
}
func (dst *Ship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ship.Merge(dst, src)
}
func (m *Ship) XXX_Size() int {
	return xxx_messageInfo_Ship.Size(m)
}
func (m *Ship) XXX_DiscardUnknown() {
	xxx_messageInfo_Ship.DiscardUnknown(m)
}

var xxx_messageInfo_Ship proto.InternalMessageInfo

func (m *Ship) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ship) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Ship) GetXPos() float32 {
	if m != nil {
		return m.XPos
	}
	return 0
}

func (m *Ship) GetYPos() float32 {
	if m != nil {
		return m.YPos
	}
	return 0
}

func (m *Ship) GetXVel() float32 {
	if m != nil {
		return m.XVel
	}
	return 0
}

func (m *Ship) GetYVel() float32 {
	if m != nil {
		return m.YVel
	}
	return 0
}

func (m *Ship) GetRot() float32 {
	if m != nil {
		return m.Rot
	}
	return 0
}

func (m *Ship) GetRotVel() float32 {
	if m != nil {
		return m.RotVel
	}
	return 0
}

func (m *Ship) GetBullets() []*Ship_Bullet {
	if m != nil {
		return m.Bullets
	}
	return nil
}

// TODO eventually do bullets
type Ship_Bullet struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XPos                 float32  `protobuf:"fixed32,2,opt,name=xPos,proto3" json:"xPos,omitempty"`
	YPos                 float32  `protobuf:"fixed32,3,opt,name=yPos,proto3" json:"yPos,omitempty"`
	XVel                 float32  `protobuf:"fixed32,4,opt,name=xVel,proto3" json:"xVel,omitempty"`
	YVel                 float32  `protobuf:"fixed32,5,opt,name=yVel,proto3" json:"yVel,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ship_Bullet) Reset()         { *m = Ship_Bullet{} }
func (m *Ship_Bullet) String() string { return proto.CompactTextString(m) }
func (*Ship_Bullet) ProtoMessage()    {}
func (*Ship_Bullet) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_7bbe1fe9df4558eb, []int{1, 0}
}
func (m *Ship_Bullet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ship_Bullet.Unmarshal(m, b)
}
func (m *Ship_Bullet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ship_Bullet.Marshal(b, m, deterministic)
}
func (dst *Ship_Bullet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ship_Bullet.Merge(dst, src)
}
func (m *Ship_Bullet) XXX_Size() int {
	return xxx_messageInfo_Ship_Bullet.Size(m)
}
func (m *Ship_Bullet) XXX_DiscardUnknown() {
	xxx_messageInfo_Ship_Bullet.DiscardUnknown(m)
}

var xxx_messageInfo_Ship_Bullet proto.InternalMessageInfo

func (m *Ship_Bullet) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Ship_Bullet) GetXPos() float32 {
	if m != nil {
		return m.XPos
	}
	return 0
}

func (m *Ship_Bullet) GetYPos() float32 {
	if m != nil {
		return m.YPos
	}
	return 0
}

func (m *Ship_Bullet) GetXVel() float32 {
	if m != nil {
		return m.XVel
	}
	return 0
}

func (m *Ship_Bullet) GetYVel() float32 {
	if m != nil {
		return m.YVel
	}
	return 0
}

func (m *Ship_Bullet) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Our list of ships
type GameState struct {
	Ships                []*Ship  `protobuf:"bytes,1,rep,name=ships,proto3" json:"ships,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_7bbe1fe9df4558eb, []int{2}
}
func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (dst *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(dst, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetShips() []*Ship {
	if m != nil {
		return m.Ships
	}
	return nil
}

type ShipUpdate struct {
	RotLeft              bool     `protobuf:"varint,1,opt,name=rotLeft,proto3" json:"rotLeft,omitempty"`
	RotRight             bool     `protobuf:"varint,2,opt,name=rotRight,proto3" json:"rotRight,omitempty"`
	Thrust               bool     `protobuf:"varint,3,opt,name=thrust,proto3" json:"thrust,omitempty"`
	Fire                 bool     `protobuf:"varint,4,opt,name=fire,proto3" json:"fire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipUpdate) Reset()         { *m = ShipUpdate{} }
func (m *ShipUpdate) String() string { return proto.CompactTextString(m) }
func (*ShipUpdate) ProtoMessage()    {}
func (*ShipUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_gamestate_7bbe1fe9df4558eb, []int{3}
}
func (m *ShipUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipUpdate.Unmarshal(m, b)
}
func (m *ShipUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipUpdate.Marshal(b, m, deterministic)
}
func (dst *ShipUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipUpdate.Merge(dst, src)
}
func (m *ShipUpdate) XXX_Size() int {
	return xxx_messageInfo_ShipUpdate.Size(m)
}
func (m *ShipUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ShipUpdate proto.InternalMessageInfo

func (m *ShipUpdate) GetRotLeft() bool {
	if m != nil {
		return m.RotLeft
	}
	return false
}

func (m *ShipUpdate) GetRotRight() bool {
	if m != nil {
		return m.RotRight
	}
	return false
}

func (m *ShipUpdate) GetThrust() bool {
	if m != nil {
		return m.Thrust
	}
	return false
}

func (m *ShipUpdate) GetFire() bool {
	if m != nil {
		return m.Fire
	}
	return false
}

func init() {
	proto.RegisterType((*GenericMessage)(nil), "GenericMessage")
	proto.RegisterType((*Ship)(nil), "Ship")
	proto.RegisterType((*Ship_Bullet)(nil), "Ship.Bullet")
	proto.RegisterType((*GameState)(nil), "GameState")
	proto.RegisterType((*ShipUpdate)(nil), "ShipUpdate")
	proto.RegisterEnum("GenericMessage_MessageTypeEnum", GenericMessage_MessageTypeEnum_name, GenericMessage_MessageTypeEnum_value)
}

func init() { proto.RegisterFile("gamestate.proto", fileDescriptor_gamestate_7bbe1fe9df4558eb) }

var fileDescriptor_gamestate_7bbe1fe9df4558eb = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x9d, 0xa4, 0x69, 0xd3, 0xd3, 0xd2, 0xd6, 0x01, 0x65, 0x58, 0x05, 0x4b, 0x2e, 0x24,
	0x57, 0xb9, 0x58, 0x9f, 0xa0, 0x62, 0x88, 0x82, 0x95, 0x32, 0xc9, 0xae, 0x97, 0x25, 0x6b, 0x66,
	0x9b, 0x81, 0xfc, 0x63, 0x66, 0x0a, 0xdb, 0x17, 0xf0, 0x79, 0x7c, 0x19, 0xdf, 0x47, 0xe6, 0x24,
	0x75, 0x57, 0xb7, 0x77, 0xdf, 0xf9, 0xf5, 0x1b, 0xe6, 0x77, 0x9a, 0x81, 0xe5, 0x21, 0xaf, 0x85,
	0x36, 0xb9, 0x11, 0x51, 0xa7, 0x5a, 0xd3, 0x06, 0xbf, 0x08, 0x2c, 0x12, 0xd1, 0x08, 0x25, 0x7f,
	0x6c, 0x85, 0xd6, 0xf9, 0x41, 0xd0, 0x0d, 0xcc, 0xea, 0x3e, 0x66, 0xa7, 0x4e, 0x30, 0xb2, 0x26,
	0xe1, 0xe2, 0xfa, 0x5d, 0xf4, 0x6f, 0x2b, 0xda, 0x3e, 0x56, 0xe2, 0xe6, 0x58, 0xf3, 0xa7, 0x67,
	0x28, 0x85, 0x51, 0x91, 0x9b, 0x9c, 0x39, 0x6b, 0x12, 0xce, 0x39, 0xe6, 0x20, 0x81, 0xe5, 0x7f,
	0x67, 0xe8, 0x2b, 0x78, 0x99, 0x6c, 0xb6, 0xf1, 0x3e, 0xcd, 0x36, 0x59, 0xbc, 0xbf, 0xd9, 0x7d,
	0xda, 0x64, 0xf1, 0xea, 0x05, 0x5d, 0xc2, 0x2c, 0xfd, 0xfc, 0x65, 0x77, 0x06, 0x84, 0xce, 0xc1,
	0xff, 0x16, 0x7f, 0xdf, 0x5b, 0xb8, 0x72, 0x82, 0xdf, 0x0e, 0x8c, 0xd2, 0x52, 0x76, 0xf6, 0x96,
	0x26, 0xaf, 0x7b, 0xc3, 0x29, 0xc7, 0x4c, 0x17, 0xe0, 0xc8, 0x02, 0xef, 0xf5, 0xb8, 0x23, 0x0b,
	0xdb, 0x79, 0xd8, 0xb5, 0x9a, 0xb9, 0x6b, 0x12, 0x3a, 0x1c, 0xb3, 0x65, 0x27, 0xcb, 0x46, 0x3d,
	0x3b, 0x0d, 0xec, 0xe1, 0x56, 0x54, 0xcc, 0x1b, 0x7a, 0xb7, 0xa2, 0xc2, 0x9e, 0x65, 0xe3, 0xa1,
	0x67, 0xd9, 0x0a, 0x5c, 0xd5, 0x1a, 0x36, 0x41, 0x64, 0x23, 0x7d, 0x0d, 0x63, 0xd5, 0x1a, 0xdb,
	0xf3, 0x11, 0x0e, 0x13, 0x7d, 0x0f, 0x93, 0xbb, 0x63, 0x55, 0x09, 0xa3, 0xd9, 0x74, 0xed, 0x86,
	0xb3, 0xeb, 0x79, 0x64, 0xad, 0xa3, 0x8f, 0x08, 0xf9, 0xf9, 0xc7, 0xab, 0x9f, 0x04, 0xc6, 0x3d,
	0x1b, 0xe4, 0xc9, 0x33, 0x79, 0xe7, 0x82, 0xbc, 0x7b, 0x41, 0x7e, 0x74, 0x41, 0xde, 0x7b, 0x22,
	0xff, 0x16, 0xa6, 0x46, 0xe2, 0xf7, 0xaf, 0x3b, 0xdc, 0xca, 0xe5, 0x8f, 0x20, 0x08, 0x61, 0x9a,
	0xe4, 0xb5, 0x48, 0xed, 0xeb, 0xa0, 0x6f, 0xc0, 0xd3, 0xa5, 0xec, 0x34, 0x23, 0xe8, 0xee, 0xa1,
	0x3b, 0xef, 0x59, 0xd0, 0x00, 0xd8, 0xf1, 0xa6, 0x2b, 0x6c, 0x95, 0xc1, 0x44, 0xb5, 0xe6, 0xab,
	0xb8, 0x37, 0xa8, 0xee, 0xf3, 0xf3, 0x48, 0xaf, 0xc0, 0x57, 0xad, 0xe1, 0xf2, 0x50, 0x1a, 0xdc,
	0xc1, 0xe7, 0x7f, 0x67, 0xfb, 0xb7, 0x99, 0x52, 0x1d, 0xb5, 0xc1, 0x4d, 0x7c, 0x3e, 0x4c, 0xd6,
	0xfb, 0x5e, 0x2a, 0x81, 0xbb, 0xf8, 0x1c, 0xf3, 0xdd, 0x18, 0xdf, 0xea, 0x87, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xcc, 0x4b, 0x17, 0x44, 0xbe, 0x02, 0x00, 0x00,
}
